project:
  type: website

website:
  title: "Suicide Squad"
  site-url: "https://suicidesquad.netlify.app/"
  sidebar:
    background: "#A8D8CA"
    pinned: true
    align: center
    tools:
      - icon: house-fill
        href: "https://suicidesquad.netlify.app/"
        text: "Home"
      - icon: github
        href: "https://github.com/magdalenecjw/SuicideSquad"
        text: "GitHub"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: "Proposal/ProposalPage.html"
        text: "Proposal"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

